// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab3.Data.Context;

#nullable disable

namespace lab3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223031023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lab3.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("lab3.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 5,
                            Description = "Gaming Laptop",
                            Price = 15000m,
                            Title = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 10,
                            Description = "Android Smartphone",
                            Price = 9000m,
                            Title = "Smartphone"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Count = 15,
                            Description = "Wireless Headphones",
                            Price = 1200m,
                            Title = "Headphones"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Count = 20,
                            Description = "Cotton T-Shirt",
                            Price = 300m,
                            Title = "T-Shirt"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Count = 12,
                            Description = "Blue Denim Jeans",
                            Price = 800m,
                            Title = "Jeans"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Count = 7,
                            Description = "Winter Jacket",
                            Price = 1500m,
                            Title = "Jacket"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Count = 25,
                            Description = "Learn C# Programming",
                            Price = 450m,
                            Title = "C# Book"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Count = 18,
                            Description = "Master ASP.NET Core",
                            Price = 550m,
                            Title = "ASP.NET Core Book"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Count = 6,
                            Description = "800W Microwave Oven",
                            Price = 3200m,
                            Title = "Microwave"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Count = 4,
                            Description = "Double Door Fridge",
                            Price = 12000m,
                            Title = "Refrigerator"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Count = 30,
                            Description = "Professional Football",
                            Price = 250m,
                            Title = "Football"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Count = 9,
                            Description = "Carbon Fiber Racket",
                            Price = 1100m,
                            Title = "Tennis Racket"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Count = 14,
                            Description = "Digital Wrist Watch",
                            Price = 600m,
                            Title = "Watch"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Count = 16,
                            Description = "Laptop Backpack",
                            Price = 700m,
                            Title = "Backpack"
                        });
                });

            modelBuilder.Entity("lab3.Models.Product", b =>
                {
                    b.HasOne("lab3.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("lab3.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
